name: gen_website

on:
  push:
  release:
    types: [published]
    branches: [main]

  workflow_dispatch:

jobs:
  gen_doc:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: merge main -> docs
        uses: devmasx/merge-branch@master
        with:
          github_token: ${{ github.token }}
          type: now
          from_branch: main
          target_branch: docs
      - uses: actions/checkout@v2
        with:
          ref: docs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install esbuild -g
      - run: npm run build:doc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: docs
          commit_message: '[Automated] gen website'
